// /reports — client-rendered index of reports generated by this browser.
// No server state: the list is built from localStorage (same key the AssistantDock writes).
// SSR renders an empty shell; the client fills it on mount.

import { useEffect, useState } from 'react';
import { Link } from 'react-router';
import { PageHeader } from '../components/PageHeader';
import { loadTranscript } from '../lib/assistant-dock/storage';
import { reportOutputFromMessage } from '../lib/assistant-dock/report-projection';

interface ReportRef {
  id: string;
  title: string;
  url: string;
}

function extractReportRefs(): ReportRef[] {
  const messages = loadTranscript();
  const refs: ReportRef[] = [];
  const seen = new Set<string>();

  for (const message of [...messages].reverse()) {
    if (message.role !== 'assistant') continue;
    const output = reportOutputFromMessage(message);
    if (!output?.ok) continue;
    if (!seen.has(output.id)) {
      seen.add(output.id);
      refs.push({ id: output.id, title: output.report.title, url: output.url });
    }
  }

  return refs;
}

function ReportsClient() {
  const [refs, setRefs] = useState<ReportRef[]>([]);

  useEffect(() => {
    setRefs(extractReportRefs());
  }, []);

  if (refs.length === 0) {
    return (
      <p className="muted">
        Нямате генерирани справки в този браузър. Задайте въпрос на AI асистента, за да създадете
        първата си справка.
      </p>
    );
  }

  return (
    <div className="table-wrap tbl-cards reports-index">
      <table>
        <thead>
          <tr>
            <th scope="col" className="num">#</th>
            <th scope="col">Справка</th>
          </tr>
        </thead>
        <tbody>
          {refs.map((r, i) => (
            <tr key={r.id}>
              <td className="rank cell-rank" data-label="#">{i + 1}</td>
              <td className="cell-title" data-label="Справка">
                <Link to={r.url ?? `/reports/${r.id}`}>{r.title}</Link>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function meta() {
  return [
    { title: 'Моите справки — СИГМА' },
    { name: 'robots', content: 'noindex' },
  ];
}

export default function ReportsIndex() {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

  return (
    <main id="main">
      <PageHeader
        kicker="AI Асистент"
        title="Моите справки"
        lede="Справки, генерирани от AI асистента в този браузър."
      />
      {mounted ? <ReportsClient /> : null}
    </main>
  );
}
