// /reports — client-rendered index of reports generated by this browser.
// No server state: the list is built from localStorage (same key the ChatDock writes).
// SSR renders an empty shell; the client fills it on mount.

import { useEffect, useState } from 'react';
import { Link } from 'react-router';
import { PageHeader } from '../components/PageHeader';

const STORAGE_KEY = 'sigma:chat';

const MOCK_REFS: ReportRef[] = [
  {
    id: 'mock-medisistem-2024',
    title: 'Медисистем ЕООД — профил на компанията с най-много договора',
    url: '/reports/mock-medisistem-2024',
  },
];

interface ReportRef {
  id: string;
  title: string;
  url: string;
}

function extractReportRefs(raw: string | null): ReportRef[] {
  if (!raw) return [];
  try {
    const messages = JSON.parse(raw) as Array<{
      role: string;
      parts?: Array<{ type: string; toolInvocation?: { toolName: string; state: string; result?: { id: string; title: string; url: string } } }>;
    }>;
    const refs: ReportRef[] = [];
    const seen = new Set<string>();
    for (const m of messages) {
      if (m.role !== 'assistant' || !m.parts) continue;
      for (const part of m.parts) {
        if (
          part.type === 'tool-invocation' &&
          part.toolInvocation?.toolName === 'emit_report' &&
          part.toolInvocation.state === 'result' &&
          part.toolInvocation.result?.id
        ) {
          const { id, title, url } = part.toolInvocation.result;
          if (!seen.has(id)) {
            seen.add(id);
            refs.push({ id, title, url });
          }
        }
      }
    }
    return refs.reverse(); // newest first
  } catch {
    return [];
  }
}

function ReportsClient() {
  const [refs, setRefs] = useState<ReportRef[]>([]);

  useEffect(() => {
    const fromStorage = extractReportRefs(localStorage.getItem(STORAGE_KEY));
    const storageIds = new Set(fromStorage.map((r) => r.id));
    const mocks = MOCK_REFS.filter((r) => !storageIds.has(r.id));
    setRefs([...fromStorage, ...mocks]);
  }, []);

  if (refs.length === 0) {
    return (
      <p className="muted">
        Нямате генерирани справки в този браузър. Задайте въпрос на AI асистента, за да създадете
        първата си справка.
      </p>
    );
  }

  return (
    <div className="table-wrap tbl-cards reports-index">
      <table>
        <thead>
          <tr>
            <th scope="col" className="num">#</th>
            <th scope="col">Справка</th>
          </tr>
        </thead>
        <tbody>
          {refs.map((r, i) => (
            <tr key={r.id}>
              <td className="rank cell-rank" data-label="#">{i + 1}</td>
              <td className="cell-title" data-label="Справка">
                <Link to={r.url ?? `/reports/${r.id}`}>{r.title}</Link>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function meta() {
  return [
    { title: 'Моите справки — СИГМА' },
    { name: 'robots', content: 'noindex' },
  ];
}

export default function ReportsIndex() {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

  return (
    <main id="main">
      <PageHeader
        kicker="AI Асистент"
        title="Моите справки"
        lede="Справки, генерирани от AI асистента в този браузър."
      />
      {mounted ? <ReportsClient /> : null}
    </main>
  );
}
